site_name: Center for Computational Mathematics
 University of Colorado Denver 
site_url: https://ccm-docs.readthedocs.io/en/latest/ 
repo_url: https://github.com/ccmucdenver/ccm-docs 
edit_uri: edit/main/docs/
site_description: Documentation for computing resources at the CCM
theme:
  name: readthedocs
  highlightjs: true
  features:
    - navigation.instant
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
    - Welcome: index.md
    - Terms and Conditions: TermsandConditions.md
    - Updates:  updates.md
    - Accounts: accounts.md
    - User Guide:
        - Start Here:
            - Overview: overview.md
            - Clusters Guide: clusters_guide.md
            - Examples: examples.md
        - Graphical Access:
            - JupyterHub: jupyterhub.md
            - Remote Desktop: remote_desktop.md
        - Software and Environments:
            - Environment Modules: modules.md
            - Conda and Python: conda.md
            - Singularity Containers: singularity.md
            - Apache Spark: spark.md
        - Data Transfer:
            - Globus File Transfer: globus.md
    - External Resources: external.md
    - Facilities, Equipment, and Other Resources: facilities.md
    - How to Edit: pull_request.md
